[package]
name = "gdom"
version = "0.1.0"
description = "Google Drive Owner Migrator"
authors = ["phucrio"]
license = "GPL-3.0-or-later"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "gdom_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
oauth2 = { version = "5.0.0", default-features = false, features = ["timing-resistant-secret-traits"] }
open = "5"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false, features = ["derive", "runtime-tokio", "sqlite-bundled"] }
tauri = { version = "2", features = [] }
tokio = { version = "1.53.1", features = ["io-util", "macros", "net", "rt", "test-util", "time"] }
url = "2.5.8"

[dev-dependencies]
keyring-core = "1.0.0"
serde_json = "1"

[target.'cfg(target_os = "windows")'.dependencies]
keyring-core = "1.0.0"
windows-native-keyring-store = { version = "1.1.0", default-features = false }
